name: "steakify-backend"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: steakify-db
    ports:
      - "5432:5432"